// Package pdf generates polished PDF research reports from PubMed agent summaries.
// It uses headless Chrome (chromedp) to render an HTML template to PDF, with
// the HTML template optionally generated by an LLM from a plain-English style prompt.
package pdf

import (
	"bytes"
	"context"
	"fmt"
	"html/template"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/chromedp/cdproto/page"
	"github.com/chromedp/chromedp"
	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/extension"
	"github.com/yuin/goldmark/renderer/html"
	"google.golang.org/adk/model"
	"google.golang.org/genai"
)

// ArticleRef holds the metadata for a single article used in the PDF reference list.
type ArticleRef struct {
	PMID    string
	Title   string
	Journal string
	Date    string
}

// PDFRequest carries all inputs needed to generate a report PDF.
type PDFRequest struct {
	Question    string
	Summary     string       // raw markdown summary from the agent
	Articles    []ArticleRef // articles fetched for this session
	OutDir      string       // directory to write the PDF file
	StylePrompt string       // plain-English style description; "" = use fallback template
}

// PDFResult is returned by Generator.Generate on success.
type PDFResult struct {
	FilePath    string
	DownloadURL string
}

// TemplateData is the data injected into the HTML template.
type TemplateData struct {
	Question   string
	Date       string
	BodyHTML   template.HTML
	References []RefEntry
}

// RefEntry is one entry in the References section.
type RefEntry struct {
	Number  int
	PMID    string
	Title   string
	Journal string
	Date    string
	URL     string
}

// Generator holds the LLM reference needed for on-the-fly template generation.
type Generator struct {
	llm model.LLM
}

// NewGenerator creates a Generator. llm is used only when StylePrompt is non-empty.
func NewGenerator(llm model.LLM) *Generator {
	return &Generator{llm: llm}
}

// Generate produces a PDF report and saves it to req.OutDir.
// It returns the file path and the download URL constructed from baseDownloadURL.
func (g *Generator) Generate(ctx context.Context, req PDFRequest, baseDownloadURL string) (PDFResult, error) {
	if err := os.MkdirAll(req.OutDir, 0o755); err != nil {
		return PDFResult{}, fmt.Errorf("pdf: create output dir: %w", err)
	}

	// 1. Resolve the HTML template (LLM-generated or built-in fallback).
	tmpl, err := g.resolveTemplate(ctx, req.StylePrompt)
	if err != nil {
		return PDFResult{}, fmt.Errorf("pdf: resolve template: %w", err)
	}

	// 2. Convert summary markdown → HTML body.
	bodyHTML, orderedRefs := convertSummary(req.Summary, req.Articles)

	// 3. Build template data.
	data := TemplateData{
		Question:   req.Question,
		Date:       time.Now().Format("2006-01-02"),
		BodyHTML:   template.HTML(bodyHTML), //nolint:gosec // HTML is agent-generated, not user input
		References: orderedRefs,
	}

	// 4. Execute the template.
	var htmlBuf bytes.Buffer
	if err := tmpl.Execute(&htmlBuf, data); err != nil {
		log.Printf("pdf: template execute error (%v), retrying with fallback", err)
		tmpl, _ = template.New("fallback").Parse(fallbackTemplate)
		htmlBuf.Reset()
		if err2 := tmpl.Execute(&htmlBuf, data); err2 != nil {
			return PDFResult{}, fmt.Errorf("pdf: fallback template execute: %w", err2)
		}
	}

	// 5. Write HTML to a temp file for chromedp to read.
	tmpHTML, err := os.CreateTemp("", "pubmed-report-*.html")
	if err != nil {
		return PDFResult{}, fmt.Errorf("pdf: create temp html: %w", err)
	}
	defer os.Remove(tmpHTML.Name())

	if _, err := tmpHTML.Write(htmlBuf.Bytes()); err != nil {
		return PDFResult{}, fmt.Errorf("pdf: write temp html: %w", err)
	}
	if err := tmpHTML.Close(); err != nil {
		return PDFResult{}, fmt.Errorf("pdf: close temp html: %w", err)
	}

	// 6. Render HTML → PDF via headless Chrome.
	pdfBytes, err := renderToPDF(ctx, "file://"+tmpHTML.Name())
	if err != nil {
		return PDFResult{}, fmt.Errorf("pdf: chromedp render: %w", err)
	}

	// 7. Write PDF to output directory.
	filename := buildFilename(req.Question)
	outPath := filepath.Join(req.OutDir, filename)
	if err := os.WriteFile(outPath, pdfBytes, 0o644); err != nil {
		return PDFResult{}, fmt.Errorf("pdf: write output: %w", err)
	}

	downloadURL := strings.TrimRight(baseDownloadURL, "/") + "/download/" + filename
	return PDFResult{FilePath: outPath, DownloadURL: downloadURL}, nil
}

// resolveTemplate returns a parsed *template.Template. If stylePrompt is non-empty
// it asks the LLM to generate an HTML template; on any error it falls back to the
// built-in template and logs a warning.
func (g *Generator) resolveTemplate(ctx context.Context, stylePrompt string) (*template.Template, error) {
	if stylePrompt == "" || g.llm == nil {
		return template.New("fallback").Parse(fallbackTemplate)
	}

	prompt := buildTemplatePrompt(stylePrompt)
	req := &model.LLMRequest{
		Contents: []*genai.Content{
			genai.NewContentFromText(prompt, "user"),
		},
	}

	raw, err := generateText(ctx, g.llm, req)
	if err != nil {
		log.Printf("pdf: LLM template generation failed (%v), using fallback", err)
		return template.New("fallback").Parse(fallbackTemplate)
	}

	// Strip any accidental markdown fences the LLM might add.
	raw = stripMarkdownFences(raw)

	tmpl, parseErr := template.New("llm").Parse(raw)
	if parseErr != nil {
		log.Printf("pdf: LLM template parse failed (%v), using fallback", parseErr)
		return template.New("fallback").Parse(fallbackTemplate)
	}
	return tmpl, nil
}

// convertSummary converts markdown to HTML body and extracts an ordered reference
// list from [PMID:N](url) citation links found in the summary.
// Returns (htmlBody, []RefEntry).
func convertSummary(summaryMD string, articles []ArticleRef) (string, []RefEntry) {
	// Build a PMID→ArticleRef lookup.
	articleByPMID := make(map[string]ArticleRef, len(articles))
	for _, a := range articles {
		articleByPMID[a.PMID] = a
	}

	// Replace citation tags with superscript links and build the reference list.
	// Handles all formats the LLM may emit:
	//   [PMID:N](url)       — linked markdown form
	//   [PMID:N]            — plain form (after guard processing strips the URL)
	//   [PMID:N, M, ...]    — comma-grouped form
	var refs []RefEntry
	pmidToIdx := make(map[string]int)

	addRef := func(pmid string) int {
		if idx, seen := pmidToIdx[pmid]; seen {
			return idx
		}
		idx := len(refs) + 1
		pmidToIdx[pmid] = idx
		a := articleByPMID[pmid]
		refs = append(refs, RefEntry{
			Number:  idx,
			PMID:    pmid,
			Title:   a.Title,
			Journal: a.Journal,
			Date:    a.Date,
			URL:     "https://pubmed.ncbi.nlm.nih.gov/" + pmid + "/",
		})
		return idx
	}

	citationRe := regexp.MustCompile(`\[PMID:([\d,\s]+)\](?:\([^)]*\))?`)
	processed := citationRe.ReplaceAllStringFunc(summaryMD, func(match string) string {
		sub := citationRe.FindStringSubmatch(match)
		if len(sub) < 2 {
			return match
		}
		var result strings.Builder
		for raw := range strings.SplitSeq(sub[1], ",") {
			pmid := strings.TrimSpace(raw)
			if pmid == "" {
				continue
			}
			idx := addRef(pmid)
			fmt.Fprintf(&result, `<sup class="cite"><a href="#ref-%d">[%d]</a></sup>`, idx, idx)
		}
		return result.String()
	})

	// Also strip the plain References section that the agent appends (we re-render it).
	processed = stripAgentReferencesSection(processed)

	// Convert remaining markdown to HTML.
	md := goldmark.New(
		goldmark.WithExtensions(extension.GFM),
		goldmark.WithRendererOptions(html.WithUnsafe()),
	)
	var buf bytes.Buffer
	if err := md.Convert([]byte(processed), &buf); err != nil {
		return processed, refs // fallback: raw text
	}
	return buf.String(), refs
}

// stripAgentReferencesSection removes the agent-appended "**References**" section
// from the markdown before rendering, since the PDF template has its own references section.
var referencesHeaderRe = regexp.MustCompile(`(?mi)^[\*_]{0,2}References[\*_]{0,2}\s*\n([\s\S]*)$`)

func stripAgentReferencesSection(md string) string {
	return referencesHeaderRe.ReplaceAllString(md, "")
}

// renderToPDF uses chromedp to navigate to fileURL and print the page as PDF.
func renderToPDF(ctx context.Context, fileURL string) ([]byte, error) {
	allocCtx, cancelAlloc := chromedp.NewExecAllocator(ctx,
		append(chromedp.DefaultExecAllocatorOptions[:],
			chromedp.Flag("headless", "new"), // new headless mode preserves hyperlinks in PrintToPDF
			chromedp.Flag("disable-gpu", true),
			chromedp.Flag("no-sandbox", true),
			chromedp.Flag("disable-dev-shm-usage", true),
		)...,
	)
	defer cancelAlloc()

	taskCtx, cancelTask := chromedp.NewContext(allocCtx)
	defer cancelTask()

	var pdfBuf []byte
	if err := chromedp.Run(taskCtx,
		chromedp.Navigate(fileURL),
		chromedp.WaitReady("body", chromedp.ByQuery), // ensure page fully rendered before printing
		chromedp.ActionFunc(func(ctx context.Context) error {
			var err error
			pdfBuf, _, err = page.PrintToPDF().
				WithPrintBackground(true).
				WithPaperWidth(8.27).  // A4 width in inches
				WithPaperHeight(11.7). // A4 height in inches
				WithMarginTop(0).
				WithMarginBottom(0).
				WithMarginLeft(0).
				WithMarginRight(0).
				Do(ctx)
			return err
		}),
	); err != nil {
		return nil, err
	}
	return pdfBuf, nil
}

// buildFilename produces a safe filename like 2026-01-15_anticoagulation-therapy.pdf
func buildFilename(question string) string {
	date := time.Now().Format("2006-01-02")
	slug := slugify(question)
	if len(slug) > 50 {
		slug = slug[:50]
	}
	return date + "_" + slug + ".pdf"
}

var nonAlphanumRe = regexp.MustCompile(`[^a-z0-9]+`)

func slugify(s string) string {
	s = strings.ToLower(s)
	s = nonAlphanumRe.ReplaceAllString(s, "-")
	s = strings.Trim(s, "-")
	return s
}

// stripMarkdownFences removes ```html ... ``` or ``` ... ``` wrappers if the LLM
// accidentally includes them in its response.
func stripMarkdownFences(s string) string {
	s = strings.TrimSpace(s)
	fenceRe := regexp.MustCompile("(?s)^```(?:html)?\\s*\n?(.*?)\\s*```$")
	if m := fenceRe.FindStringSubmatch(s); len(m) == 2 {
		return strings.TrimSpace(m[1])
	}
	return s
}

// generateText calls the LLM and returns the first text part from the response.
// Kept local to this package to avoid a cross-package dependency on tools.
func generateText(ctx context.Context, llm model.LLM, req *model.LLMRequest) (string, error) {
	var lastErr error
	for resp, err := range llm.GenerateContent(ctx, req, false) {
		if err != nil {
			lastErr = err
			continue
		}
		if resp.Content == nil {
			continue
		}
		for _, part := range resp.Content.Parts {
			if part.Text != "" {
				return part.Text, nil
			}
		}
	}
	if lastErr != nil {
		return "", lastErr
	}
	return "", fmt.Errorf("model returned no text content")
}
